nginx version bump

diff --git a/nginx/auto/lib/perl/conf b/nginx/auto/lib/perl/conf
--- a/nginx/auto/lib/perl/conf
+++ b/nginx/auto/lib/perl/conf
@@ -1,5 +1,6 @@
 
 # Copyright (C) Igor Sysoev
+# Copyright (C) Nginx, Inc.
 
 
 echo "checking for perl"
@@ -11,9 +12,17 @@ NGX_PERL_VER=`$NGX_PERL -v 2>&1 | grep '^This is perl' 2>&1 \
 if test -n "$NGX_PERL_VER"; then
     echo " + perl version: $NGX_PERL_VER"
 
-    if [ "`echo 'use 5.006001; print "OK"' | $NGX_PERL 2>&1`" != OK ]; then
+    if [ "`$NGX_PERL -e 'use 5.006001; print "OK"'`" != "OK" ]; then
         echo
         echo "$0: error: perl 5.6.1 or higher is required"
+        echo
+
+        exit 1;
+    fi
+
+    if [ "`$NGX_PERL -MExtUtils::Embed -e 'print "OK"'`" != "OK" ]; then
+        echo
+        echo "$0: error: perl module ExtUtils::Embed is required"
         echo
 
         exit 1;
@@ -31,6 +40,8 @@ if test -n "$NGX_PERL_VER"; then
 
     ngx_perl_ldopts=`$NGX_PERL -MExtUtils::Embed -e ldopts`
 
+    ngx_perl_dlext=`$NGX_PERL -MConfig -e 'print $Config{dlext}'`
+
     if $NGX_PERL -V:usemultiplicity | grep define > /dev/null; then
         have=NGX_HAVE_PERL_MULTIPLICITY . auto/have
         echo " + perl interpreter multiplicity found"
@@ -42,7 +53,7 @@ if test -n "$NGX_PERL_VER"; then
     fi
 
     CORE_LINK="$CORE_LINK $ngx_perl_ldopts"
-    LINK_DEPS="$LINK_DEPS $NGX_OBJS/src/http/modules/perl/blib/arch/auto/nginx/nginx.so"
+    LINK_DEPS="$LINK_DEPS $NGX_OBJS/src/http/modules/perl/blib/arch/auto/nginx/nginx.$ngx_perl_dlext"
 
     if test -n "$NGX_PERL_MODULES"; then
         have=NGX_PERL_MODULES value="(u_char *) \"$NGX_PERL_MODULES\""
