bump  gitlib

diff --git a/libs/lib_gif/giflib/tests/makefile b/libs/lib_gif/giflib/tests/makefile
--- a/libs/lib_gif/giflib/tests/makefile
+++ b/libs/lib_gif/giflib/tests/makefile
@@ -4,78 +4,86 @@
 .SUFFIXES: .gif .rgb
 
 # This is what to do by default
-test: render-regress \
+test:
+	@$(MAKE) --quiet tap | ./tapview
+
+tap:
+	@$(MAKE) --quiet tapstream | tee taplog$$$$; echo "1..$$(grep ok  taplog$$$$ | wc -l)"; rm taplog$$$$
+
+tapstream: render-regress \
+	gif2rgb-regress \
 	gifbuild-regress \
 	gifclrmp-regress \
 	gifecho-regress \
 	giffilter-regress \
 	giffix-regress \
+	gifinto-regress \
 	gifsponge-regress \
 	giftext-regress \
 	giftool-regress \
 	gifwedge-regress
-	@echo "No output is good news"
 
 rebuild: render-rebuild \
 		gif2rgb-rebuild \
 		gifclrmp-rebuild \
 		gifecho-rebuild \
 		giffix-rebuild \
+		gifinto-rebuild \
 		giftext-rebuild \
 		gifwedge-rebuild
 
-UTILS = ../util
+UTILS = ..
 PICS = ../pic
+GIF2RGB = ../gif2rgb
+
+$(GIF2RGB):
+	@$(MAKE) -C .. gif2rgb
 
 GIFS := $(shell ls ../pic/*.gif)
 
 # Test decompression and rendering by unpacking images,
 # converting them to RGB, and comparing that result to a check file.
-render-regress:
+render-regress: $(GIF2RGB)
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "Testing RGB rendering of $${test}" >&2; \
-	    $(UTILS)/gif2rgb -1 -o /tmp/regress $${test} 2>&1; \
-	    then cmp $${stem}.rgb /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	    $(UTILS)/gif2rgb -1 <$${test} | ./cmpdiffer "gif2rgb: test of $${test}" $${stem}.rgb; \
 	done
-	@rm -f /tmp/regress
-render-rebuild:
+render-rebuild: $(GIF2RGB)
 	@for test in $(GIFS); do \
 		stem=`basename $${test} | sed -e "s/.gif$$//"`; \
 		echo "Remaking $${stem}.rgb"; \
 		$(UTILS)/gif2rgb -1 -o $${stem}.rgb $${test}; \
 	done
 
-gif2rgb-rebuild:
+gif2rgb-regress: $(GIF2RGB)
+	@$(UTILS)/gif2rgb -c 3 -s 100 100 <gifgrid.rgb | $(UTILS)/gifbuild -d | sed "/sort flag/s/off/on/" | ./tapdiffer "checking gif2rgb idempotency" gifgrid.ico
+gif2rgb-rebuild: $(GIF2RGB)
 	@echo "Rebuilding gif2rgb checkfile."
 	@$(UTILS)/gif2rgb -c 3 -s 100 100 <gifgrid.rgb | $(UTILS)/gifbuild -d >gifgrid.ico
-gif2rgb-regress:
-	@echo "gif2rgb: Checking idempotency"
-	@$(UTILS)/gif2rgb -c 3 -s 100 100 <gifgrid.rgb | $(UTILS)/gifbuild -d | diff -u gifgrid.ico -
 
 gifbuild-regress:
-	@echo "gifbuild: basic sanity check"
-	@$(UTILS)/gifbuild -d <$(PICS)/treescap.gif | diff -u treescap.ico -
-	@echo "gifbuild: Checking idempotency on an icon file."
-	@$(UTILS)/gifbuild <$(PICS)/sample.ico | $(UTILS)/gifbuild -d >/tmp/sample-1.ico; $(UTILS)/gifbuild </tmp/sample-1.ico | $(UTILS)/gifbuild -d >/tmp/sample-2.ico; diff -u /tmp/sample-1.ico /tmp/sample-2.ico; rm /tmp/sample-*.ico
-	@echo "gifbuild: Checking idempotency on an animation."
-	@$(UTILS)/gifbuild -d <$(PICS)/fire.gif >/tmp/fire1.ico
-	@$(UTILS)/gifbuild </tmp/fire1.ico >/tmp/fire2.gif
-	@$(UTILS)/gifbuild -d </tmp/fire2.gif >/tmp/fire2.ico
-	@diff -u /tmp/fire1.ico /tmp/fire2.ico
+	@$(UTILS)/gifbuild -d <$(PICS)/treescap.gif | ./tapdiffer "gifbuild: basic sanity check" treescap.ico
+	@$(UTILS)/gifbuild <$(PICS)/sample.ico | $(UTILS)/gifbuild -d > $@.sample-1.ico; $(UTILS)/gifbuild < $@.sample-1.ico | $(UTILS)/gifbuild -d > $@.sample-2.ico;
+	@./tapdiffer <$@.sample-1.ico "gifbuild: Checking idempotency on an icon file." $@.sample-2.ico; rm $@.sample-?.ico
+	@$(UTILS)/gifbuild -d <$(PICS)/fire.gif > $@.fire1.ico
+	@$(UTILS)/gifbuild < $@.fire1.ico > $@.fire2.gif
+	@$(UTILS)/gifbuild -d < $@.fire2.gif > $@.fire2.ico
+	@./tapdiffer <$@.fire1.ico "gifbuild: Checking idempotency on an animation." $@.fire2.ico
+	@rm -f $@.fire1.ico  $@.fire2.ico $@.fire2.gif
 
 gifclrmp-regress:
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "gifclrmap: Checking colormap of $${test}" >&2; \
-	    $(UTILS)/gifclrmp <$${test} >/tmp/regress 2>&1; \
-	    then diff -u $${stem}.map /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	    if ! $(UTILS)/gifclrmp <$${test} > $@.$${stem}.regress 2>&1; \
+	    then \
+		echo "not ok - gifclrmap: crashed on $${test}"; \
+	    else \
+		./tapdiffer <$@.$${stem}.regress "gifclrmap: Checking colormap of $${test}" $${stem}.map; \
+	    fi \
 	done
-	@rm -f /tmp/regress
+	@rm -f $@.*.regress
 gifclrmp-rebuild:
 	@for test in $(GIFS); do \
 		stem=`basename $${test} | sed -e "s/.gif$$//"`; \
@@ -87,58 +95,48 @@ gifecho-rebuild:
 	@echo "Rebuilding gifecho test."
 	@$(UTILS)/gifecho -t "foobar" | $(UTILS)/gifbuild -d >foobar.ico
 gifecho-regress:
-	@echo "gifecho: Testing gifecho behavior"
-	@$(UTILS)/gifecho -t "foobar" | $(UTILS)/gifbuild -d | diff -u foobar.ico -
+	@$(UTILS)/gifecho -t "foobar" | $(UTILS)/gifbuild -d | ./tapdiffer "gifecho: Testing gifecho behavior" foobar.ico
 
-giffilter-regress:
+giffilter-regress: $(GIF2RGB)
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "giffiltr: Testing copy of $${test}" >&2; \
-	    $(UTILS)/giffilter <$${test} | $(UTILS)/gif2rgb >/tmp/regress 2>&1; \
-	    then cmp $${stem}.rgb /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	    $(UTILS)/giffilter <$${test} | $(UTILS)/gif2rgb | ./cmpdiffer "giffiltr: copy of $${test}" "$${stem}.rgb"; \
 	done
-	@rm -f /tmp/regress
 
 giffix-rebuild:
 	@echo "Rebuilding giffix test."
 	@head --bytes=-20 <$(PICS)/treescap.gif | $(UTILS)/giffix 2>/dev/null | $(UTILS)/gifbuild -d >giffixed.ico
 giffix-regress:
-	@echo "giffix: Testing giffix behavior"
-	@head --bytes=-20 <$(PICS)/treescap.gif | $(UTILS)/giffix 2>/dev/null | $(UTILS)/gifbuild -d | diff -u giffixed.ico -
+	@head --bytes=-20 <$(PICS)/treescap.gif | $(UTILS)/giffix 2>/dev/null | $(UTILS)/gifbuild -d | ./tapdiffer "giffix: Testing giffix behavior" giffixed.ico
 
 gifinto-regress:
-	@echo "gifinto: Checking behavior on short files."
-	@rm -f /tmp/giflib.tmp
-	@$(UTILS)/gifinto <$(PICS)/porsche.gif /tmp/giflib.tmp
-	@if test ! -f /tmp/giflib.tmp; then echo "gifinto failed to create a file when it should have."; fi
-	@rm -f /tmp/giflib.tmp
-	@echo "0123456789" | $(UTILS)/gifinto /tmp/giflib.tmp 2>/dev/null
-	@if test -f /tmp/giflib.tmp; then echo "gifinto created a file when it shouldn't have."; fi
-	@rm -f /tmp/giflib.tmp
+	@rm -f $@.giflib.tmp
+	@$(UTILS)/gifinto <$(PICS)/porsche.gif $@.giflib.tmp
+	@if test ! -f $@.giflib.tmp; then echo "not ok - gifinto failed to create a file when it should have."; fi
+	@rm -f $@.giflib.tmp
+	@echo "0123456789" | $(UTILS)/gifinto $@.giflib.tmp 2>/dev/null
+	@if test -f $@.giflib.tmp; \
+	then \
+		echo "not ok - gifinto created a file when it shouldn't have."; \
+	else \
+		echo "ok - gifinto correctly refrained from file creation."; \
+	fi
+	@rm -f $@.giflib.tmp
 
-gifsponge-regress:
+gifsponge-regress: $(GIF2RGB)
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "gifsponge: Testing copy of $${test}" >&2; \
-	    $(UTILS)/gifsponge <$${test} | $(UTILS)/gif2rgb >/tmp/regress 2>&1; \
-	    then cmp $${stem}.rgb /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	    $(UTILS)/gifsponge <$${test} | $(UTILS)/gif2rgb | ./cmpdiffer "gifsponge: sink of $${test}" $${stem}.rgb; \
 	done
-	@rm -f /tmp/regress
 
 giftext-regress:
 	@for test in $(GIFS); \
 	do \
 	    stem=`basename $${test} | sed -e "s/.gif$$//"`; \
-	    if echo "giftext: Checking text dump of $${test}" >&2; \
-	    $(UTILS)/giftext <$${test} >/tmp/regress 2>&1; \
-	    then diff -u $${stem}.dmp /tmp/regress; \
-	    else echo "*** Nonzero return status on $${test}!"; exit 1; fi; \
+	    $(UTILS)/giftext <$${test} | ./cmpdiffer "text dump of $${test}" $${stem}.dmp; \
 	done
-	@rm -f /tmp/regress
 giftext-rebuild:
 	@for test in $(GIFS); do \
 		stem=`basename $${test} | sed -e "s/.gif$$//"`; \
@@ -146,17 +144,13 @@ giftext-rebuild:
 		$(UTILS)/giftext <$${test} >$${stem}.dmp; \
 	done
 
-giftool-regress:
-	@echo "giftool: Checking that expensive copy via giftool is faithful."
-	@$(UTILS)/giftool <$(PICS)/gifgrid.gif | $(UTILS)/gif2rgb | cmp - gifgrid.rgb
-	@echo "giftool: Checking that it de-interlaces correctly."
-	@$(UTILS)/giftool -i on <$(PICS)/treescap-interlaced.gif | $(UTILS)/gif2rgb | cmp - treescap.rgb
-	@echo "giftool: Checking that it interlaces correctly."
-	@$(UTILS)/giftool -i off <$(PICS)/treescap.gif | $(UTILS)/gif2rgb | cmp - treescap-interlaced.rgb
+giftool-regress: $(GIF2RGB)
+	@$(UTILS)/giftool <$(PICS)/gifgrid.gif | $(UTILS)/gif2rgb | ./cmpdiffer "giftool: expensive copy via giftool" gifgrid.rgb
+	@$(UTILS)/giftool -i on <$(PICS)/treescap-interlaced.gif | $(UTILS)/gif2rgb | ./cmpdiffer "giftool: deinterlace" treescap.rgb
+	@$(UTILS)/giftool -i off <$(PICS)/treescap.gif | $(UTILS)/gif2rgb | ./cmpdiffer "giftool: interlace" treescap-interlaced.rgb
 
 gifwedge-rebuild:
 	@echo "Remaking the gifwedge test."
 	@$(UTILS)/gifwedge >wedge.gif
 gifwedge-regress:
-	@echo "gifwedge: Checking wedge generation."
-	@$(UTILS)/gifwedge | cmp - wedge.gif
+	@$(UTILS)/gifwedge | ./cmpdiffer "gifwedge: wedge generation." wedge.gif
